version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastserver-api
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0
    container_name: fastserver-mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=mwt
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_mwt_password
      - MYSQL_DATABASE=test
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    secrets:
      - mysql_mwt_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$(cat /run/secrets/mysql_root_password)",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
    name: fastserver-network

volumes:
  mysql_data:
    name: fastserver-mysql-data

secrets:
  mysql_mwt_password:
    file: ./secrets/mysql_mwt_password.txt
